<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Asignatura;

class AsignaturaSeeder extends Seeder
{
    public function run(): void
    {
        $asignaturas = [
            // 1. PROFESIONAL EN ADMINISTRACIÓN DE EMPRESAS
            ['codigo' => '11701111', 'nombre' => 'Procesos Matemáticos'],
            ['codigo' => '11701513', 'nombre' => 'Cronograma Jurídico Constitucional Institucional'],
            ['codigo' => '11701225', 'nombre' => 'Principios de Organización'],
            ['codigo' => '11701325', 'nombre' => 'Principios Básicos de Contabilidad'],
            ['codigo' => '11701632', 'nombre' => 'Herramientas Didácticas y Didácticas de la Educación a Distancia'],
            ['codigo' => '11702111', 'nombre' => 'Procesos Estadísticos y Probabilísticos'],
            ['codigo' => '11702225', 'nombre' => 'Planeación Empresarial'],
            ['codigo' => '11702325', 'nombre' => 'Procedimientos Contables en el Manejo de Activos'],
            ['codigo' => '11701421', 'nombre' => 'Agentes Microeconómicos'],
            ['codigo' => '11702631', 'nombre' => 'Ética y Técnicas de Investigación'],
            ['codigo' => '11703111', 'nombre' => 'Árgebra y Programación Lineal'],
            ['codigo' => '11702531', 'nombre' => 'Bases Jurídicas de la Actividad Empresarial'],
            ['codigo' => '11703225', 'nombre' => 'Organización Empresarial'],
            ['codigo' => '11703325', 'nombre' => 'Procedimientos Contables en el Manejo de Pasivos'],
            ['codigo' => '11702421', 'nombre' => 'Agentes Macroeconómicos'],
            ['codigo' => '11703532', 'nombre' => 'Inglés I'],
            ['codigo' => '11703631', 'nombre' => 'Comprensión de Texto y Lectura Crítica'],
            ['codigo' => '11704111', 'nombre' => 'Investigación de Operaciones'],
            ['codigo' => '11704225', 'nombre' => 'Dirección y Control'],
            ['codigo' => '11704325', 'nombre' => 'Procedimientos Contables de Patrimonio y Sociedades'],
            ['codigo' => '11703421', 'nombre' => 'Mercado de Capitales'],
            ['codigo' => '11704632', 'nombre' => 'Inglés II'],
            ['codigo' => '11704731', 'nombre' => 'Comprensión de Texto y Lectura Crítica (Admón)'],
            ['codigo' => '11705625', 'nombre' => 'Creatividad y Emprendimiento Empresarial'],
            ['codigo' => '11705125', 'nombre' => 'Administración de la Producción'],
            ['codigo' => '11705325', 'nombre' => 'Sistema de Costos'],
            ['codigo' => '11705425', 'nombre' => 'Conocimientos Básicos Tributarios en la Gerencia Empresarial'],
            ['codigo' => '11705632', 'nombre' => 'Inglés III'],
            ['codigo' => '11705731', 'nombre' => 'Razonamiento Matemático'],
            ['codigo' => '11706225', 'nombre' => 'Salud y Seguridad en el Trabajo'],
            ['codigo' => '11706325', 'nombre' => 'El Presupuesto como Herramienta Gerencial'],
            ['codigo' => '11704421', 'nombre' => 'Matemáticas Financieras'],
            ['codigo' => '11706223', 'nombre' => 'Herramientas Tecnológicas Aplicadas a Procesos Administrativos'],
            ['codigo' => '11705332', 'nombre' => 'Inglés IV'],
            ['codigo' => '11707631', 'nombre' => 'Psicología Organizacional'],
            ['codigo' => '11706331', 'nombre' => 'Presaber Específico'],
            ['codigo' => '11707225', 'nombre' => 'Gerencia de la Calidad'],
            ['codigo' => '11707121', 'nombre' => 'Administración Pública'],
            ['codigo' => '11707325', 'nombre' => 'Electiva'],
            ['codigo' => '11707425', 'nombre' => 'Análisis Financiero en el Área Administrativa'],
            ['codigo' => '11707732', 'nombre' => 'Inglés V'],
            ['codigo' => '11706125', 'nombre' => 'Administración del Talento Humano'],
            ['codigo' => '11708225', 'nombre' => 'Electiva II'],
            ['codigo' => '11707525', 'nombre' => 'Formulación y Evaluación de Proyectos'],
            ['codigo' => '11708121', 'nombre' => 'Administración Finca Raíz'],
            ['codigo' => '11708325', 'nombre' => 'Normas de Auditoría y Conceptos de Control'],
            ['codigo' => '11708533', 'nombre' => 'Proyecto de Investigación'],
            ['codigo' => '11708632', 'nombre' => 'Inglés VI'],
            ['codigo' => '11709125', 'nombre' => 'Procesos Gerenciales en la Administración'],
            ['codigo' => '11709325', 'nombre' => 'Gerencia Financiera'],
            ['codigo' => '11709223', 'nombre' => 'Práctica Empresarial'],
            ['codigo' => '11709433', 'nombre' => 'Desarrollo del Proyecto de Investigación'],
            ['codigo' => '11708631', 'nombre' => 'Leyes Éticas y Morales'],

            // 2. PROFESIONAL EN DISEÑO VISUAL (Códigos inventados provisionales)
            ['codigo' => 'DV-01', 'nombre' => 'Diseño Básico I'],
            ['codigo' => 'DV-02', 'nombre' => 'Expresión I'],
            ['codigo' => 'DV-03', 'nombre' => 'Idiomas I'],
            ['codigo' => 'DV-04', 'nombre' => 'Diseño Digital I'],
            ['codigo' => 'DV-05', 'nombre' => 'Historia del Diseño I'],
            ['codigo' => 'DV-06', 'nombre' => 'Técnicas de Estudio (Diseño)'],
            ['codigo' => 'DV-07', 'nombre' => 'Constitución y Cátedra para la Paz'],
            ['codigo' => 'DV-08', 'nombre' => 'Diseño Básico II'],
            ['codigo' => 'DV-09', 'nombre' => 'Expresión II'],
            ['codigo' => 'DV-10', 'nombre' => 'Comunicación Oral y Escrita'],
            ['codigo' => 'DV-11', 'nombre' => 'Idiomas II'],
            ['codigo' => 'DV-12', 'nombre' => 'Diseño Digital II'],
            ['codigo' => 'DV-13', 'nombre' => 'Historia del Diseño II'],
            ['codigo' => 'DV-14', 'nombre' => 'Ética (Diseño)'],
            ['codigo' => 'DV-15', 'nombre' => 'Diseño Básico III'],
            ['codigo' => 'DV-16', 'nombre' => 'Expresión III'],
            ['codigo' => 'DV-17', 'nombre' => 'Idiomas III'],
            ['codigo' => 'DV-18', 'nombre' => 'Diseño Digital III'],
            ['codigo' => 'DV-19', 'nombre' => 'Tipografía'],
            ['codigo' => 'DV-20', 'nombre' => 'Fundamentos Filosóficos del Diseño'],
            ['codigo' => 'DV-21', 'nombre' => 'Costos y Presupuestos (Diseño)'],
            ['codigo' => 'DV-22', 'nombre' => 'Proyecto de Diseño I'],
            ['codigo' => 'DV-23', 'nombre' => 'Taller de Diseño Editorial'],
            ['codigo' => 'DV-24', 'nombre' => 'Comunicación Visual'],
            ['codigo' => 'DV-25', 'nombre' => 'Idiomas IV'],
            ['codigo' => 'DV-26', 'nombre' => 'Diseño Digital IV'],
            ['codigo' => 'DV-27', 'nombre' => 'Fotografía I'],
            ['codigo' => 'DV-28', 'nombre' => 'Diseño de la Información Visual'],
            ['codigo' => 'DV-29', 'nombre' => 'Metodología de la Investigación (Diseño)'],
            ['codigo' => 'DV-30', 'nombre' => 'Procesos Gráficos'],
            ['codigo' => 'DV-31', 'nombre' => 'Proyecto de Diseño II'],
            ['codigo' => 'DV-32', 'nombre' => 'Taller de Imagen Corporativa'],
            ['codigo' => 'DV-33', 'nombre' => 'Imagen en Movimiento'],
            ['codigo' => 'DV-34', 'nombre' => 'Idiomas V'],
            ['codigo' => 'DV-35', 'nombre' => 'Diseño Digital V'],
            ['codigo' => 'DV-36', 'nombre' => 'Fotografía II'],
            ['codigo' => 'DV-37', 'nombre' => 'Electiva I (Diseño)'],
            ['codigo' => 'DV-38', 'nombre' => 'Proyecto de Diseño III'],
            ['codigo' => 'DV-39', 'nombre' => 'Taller de Programa Señalético'],
            ['codigo' => 'DV-40', 'nombre' => 'Seminario de Grado I'],
            ['codigo' => 'DIS-VIS-COM', 'nombre' => 'Comunicación Publicitaria'],
            ['codigo' => 'DV-42', 'nombre' => 'Idiomas VI'],
            ['codigo' => 'DV-43', 'nombre' => 'Diseño Digital VI'],
            ['codigo' => 'DV-44', 'nombre' => 'Creatividad Publicitaria y Medios'],
            ['codigo' => 'DV-45', 'nombre' => 'Electiva II (Diseño)'],
            ['codigo' => 'DIS-VIS-EL4', 'nombre' => 'Electiva IV (Diseño)'],
            ['codigo' => 'DV-47', 'nombre' => 'Proyecto de Diseño IV'],
            ['codigo' => 'DV-48', 'nombre' => 'Seminario de Grado II'],
            ['codigo' => 'DV-49', 'nombre' => 'Electiva III (Diseño)'],
            ['codigo' => 'DIS-VIS-EL5', 'nombre' => 'Electiva V (Diseño)'],
            ['codigo' => 'DIS-VIS-EL6', 'nombre' => 'Electiva VI (Diseño)'],
            ['codigo' => 'DV-52', 'nombre' => 'Práctica Empresarial (Diseño)'],
            ['codigo' => 'DV-53', 'nombre' => 'Formulación y Evaluación de Proyectos (Diseño)'],
            ['codigo' => 'DV-54', 'nombre' => 'Habilidades Gerenciales I'],
            ['codigo' => 'DV-55', 'nombre' => 'Proyecto de Diseño V'],
            ['codigo' => 'DV-56', 'nombre' => 'Desarrollo del Proyecto de Grado'],
            ['codigo' => 'DIS-VIS-HG2', 'nombre' => 'Habilidades Gerenciales II'],

            // 3. PROFESIONAL EN SEGURIDAD Y SALUD EN EL TRABAJO (SST)
            ['codigo' => 'GPS-RAP5', 'nombre' => 'Matemática Aplicada'],
            ['codigo' => 'CR1-RAP1', 'nombre' => 'Química Aplicada'],
            ['codigo' => 'CPS-RAP3', 'nombre' => 'Fundamentos de Anatomía'],
            ['codigo' => 'CPS-RAP5', 'nombre' => 'Introducción a la Gestión de Riesgos Laborales'],
            ['codigo' => 'CPS-RAP5-LEG', 'nombre' => 'Legislación en Riesgos Laborales y Ambientales'],
            ['codigo' => 'CP1-RAP1', 'nombre' => 'Ética Profesional'],
            ['codigo' => 'CF4-RAF4', 'nombre' => 'Constitución y Cátedra de la Paz'],
            ['codigo' => 'CF4-RAP5', 'nombre' => 'Lengua Extranjera Nivel Básico I'],
            ['codigo' => 'CP3-RAP3', 'nombre' => 'Técnicas de Estudio (SST)'],
            ['codigo' => 'CPE-RAPE', 'nombre' => 'Estadística Descriptiva'],
            ['codigo' => 'SST-BIO-01', 'nombre' => 'Bioquímica'],
            ['codigo' => 'SST-FIS-01', 'nombre' => 'Fundamentos de Fisiología'],
            ['codigo' => 'SST-FAP-01', 'nombre' => 'Física Aplicada'],
            ['codigo' => 'SST-PBIO-01', 'nombre' => 'Peligros y Riesgos Biológicos'],
            ['codigo' => 'SST-PSIC-01', 'nombre' => 'Peligros y Riesgos Psicosociales'],
            ['codigo' => 'SST-BIOM-01', 'nombre' => 'Peligros y Riesgos Biomecánicos'],
            ['codigo' => 'CPE-RAPE-COM', 'nombre' => 'Técnicas y Comunicación Asertiva'],
            ['codigo' => 'CF4-BAE', 'nombre' => 'Lengua Extranjera Nivel Básico II'],
            ['codigo' => 'CPE-RAP7', 'nombre' => 'Bioestadística'],
            ['codigo' => 'CP2-RAP2', 'nombre' => 'Peligro Químico y Riesgos con Materiales Peligrosos'],
            ['codigo' => 'SST-PFIS-01', 'nombre' => 'Peligro y Riesgos Físicos'],
            ['codigo' => 'SST-ERG-01', 'nombre' => 'Riesgo y Ergonomía'],
            ['codigo' => 'CP2-RAP2-ELEC', 'nombre' => 'Peligro y Riesgos Eléctricos'],
            ['codigo' => 'CP2-RAP2-LOC', 'nombre' => 'Peligro y Riesgos Locativos'],
            ['codigo' => 'CP2-RAP2-MEC', 'nombre' => 'Peligro y Riesgos Mecánicos'],
            ['codigo' => 'CP1-RAP2', 'nombre' => 'Seguridad Física Empresarial'],
            ['codigo' => 'CPE-RAP7-TAL', 'nombre' => 'Gestión del Talento Humano (SST)'],
            ['codigo' => 'SST-TOX-01', 'nombre' => 'Toxicología Ocupacional'],
            ['codigo' => 'CP2-RAP2-BRIG', 'nombre' => 'Brigadas de Emergencia'],
            ['codigo' => 'SST-HIG1-01', 'nombre' => 'Higiene Industrial I'],
            ['codigo' => 'CP1-RAP7', 'nombre' => 'Vigilancia y Epidemiológica Ocupacional'],
            ['codigo' => 'SST-MAN-01', 'nombre' => 'Mantenimiento Físico Preventivo'],
            ['codigo' => 'CP1-RAP6', 'nombre' => 'Administración de Riesgos'],
            ['codigo' => 'CP4-RAP6', 'nombre' => 'Herramientas Informáticas Aplicadas I'],
            ['codigo' => 'CF4-RAE', 'nombre' => 'Lengua Extranjera Nivel Intermedio I'],
            ['codigo' => 'SST-MET-01', 'nombre' => 'Metodología de la Investigación (SST)'],
            ['codigo' => 'SST-SAN-01', 'nombre' => 'Saneamiento Básico'],
            ['codigo' => 'CP2-RAP2-EMER', 'nombre' => 'Gestión de Planes de Emergencias y Contingencia'],
            ['codigo' => 'SST-HIG2-01', 'nombre' => 'Higiene Industrial II'],
            ['codigo' => 'C2-RAP2', 'nombre' => 'Gestión de la Seguridad Industrial'],
            ['codigo' => 'CP3-RAP3-CAD', 'nombre' => 'Cadena de Custodia'],
            ['codigo' => 'CP4-RAP4', 'nombre' => 'Electiva Libre'],
            ['codigo' => 'CPS-RAP5-INF', 'nombre' => 'Herramientas Informáticas Aplicadas II'],
            ['codigo' => 'C4-RAE', 'nombre' => 'Lengua Extranjera Nivel Intermedio II'],
            ['codigo' => 'SST-AMB-01', 'nombre' => 'Riesgos Ambientales'],
            ['codigo' => 'SP1-RAP7', 'nombre' => 'Gestión de la Medicina Preventiva y del Trabajo'],
            ['codigo' => 'SST-REH-01', 'nombre' => 'Rehabilitación y Reintegración Laboral'],
            ['codigo' => 'CPS-RAP7', 'nombre' => 'Riesgos en la Agroindustria'],
            ['codigo' => 'C2-RAP5', 'nombre' => 'Prevención en Actividades Críticas'],
            ['codigo' => 'CPE-RAP5', 'nombre' => 'Calidad en el sector salud: procesos y auditoría'],
            ['codigo' => 'CP4-RAP4-RES', 'nombre' => 'Resumen de Grado'],
            ['codigo' => 'CPS-RAP7-ISO', 'nombre' => 'Sistema de Gestión de la Seguridad y Salud en el Trabajo: Norma ISO'],
            ['codigo' => 'CP2-RAP2-DES', 'nombre' => 'Gestión del Riesgo de Desastres'],
            ['codigo' => 'CPS-RAP7-MIN', 'nombre' => 'Riesgos en la Industria Minera y de Construcción'],
            ['codigo' => 'CPS-RAP7-PET', 'nombre' => 'Riesgos en la Industria Petrolera'],
            ['codigo' => 'CPS-RAP7-ALI', 'nombre' => 'Riesgos en la Industria Alimenticia'],
            ['codigo' => 'CPE-RAP6', 'nombre' => 'Administración de Riesgos II'],
            ['codigo' => 'CP3-RAP3-SGS', 'nombre' => 'Electiva II: Sistemas de Gestión'],
            ['codigo' => 'CPE-RAPE-PER', 'nombre' => 'Control de Pérdidas'],
            ['codigo' => 'CPS-RAP6', 'nombre' => 'Lengua Extranjera Nivel Específico'],
            ['codigo' => 'SST-IOP-01', 'nombre' => 'Investigación de Operaciones (SST)'],
            ['codigo' => 'CPE-RAPE-PRAC', 'nombre' => 'Práctica Profesional (SST)'],
            ['codigo' => 'C2-RAP2-SGS3', 'nombre' => 'Electiva III: Sistemas de Gestión'],
            ['codigo' => 'C2-RAP2-DEM', 'nombre' => 'Demolición de Estructuras'],
            ['codigo' => 'CPS-RAP1-ESP', 'nombre' => 'Lengua Extranjera Nivel Específico (SST)'],
            ['codigo' => 'SST-TRAB-01', 'nombre' => 'Trabajo de Grado'],

            // 4. PROFESIONAL EN INGENIERÍA INFORMÁTICA (AG. 27-2020)
            ['codigo' => '13161111', 'nombre' => 'Conceptos y Métodos Matemáticos'],
            ['codigo' => '131611221', 'nombre' => 'Elementos Básicos de Programación'],
            ['codigo' => '131612121', 'nombre' => 'Teorías de la Ingeniería Informática'],
            ['codigo' => '131614341', 'nombre' => 'Normas de Participación Ciudadana e Institucional'],
            ['codigo' => '131615241', 'nombre' => 'Herramientas y Técnicas de Estudio - Educación a Distancia'],
            ['codigo' => '13162611', 'nombre' => 'Métodos del Cálculo Diferencial e Integral'],
            ['codigo' => '13162621011', 'nombre' => 'Postulados y Principios de la Física Mecánica'],
            ['codigo' => '131621323', 'nombre' => 'Lenguaje de Programación Funcional'],
            ['codigo' => '131622221', 'nombre' => 'Interacción de Objetos por medio de Programación'],
            ['codigo' => '131624641', 'nombre' => 'Desarrollo de Competencia Comunicativa en Segunda Lengua A1 Básico Principiante'],
            ['codigo' => '13163211', 'nombre' => 'Teoremas y Postulados Matemáticos'],
            ['codigo' => '131621011', 'nombre' => 'Diseño de Circuito Electrónico Digital'],
            ['codigo' => '131631421', 'nombre' => 'Estructuras de Datos de la Información'],
            ['codigo' => '131632323', 'nombre' => 'Aplicaciones en Entorno Gráfico con Orientada a Objetos'],
            ['codigo' => '131633631', 'nombre' => 'Conceptos y Principios de la Contabilidad General'],
            ['codigo' => '131634741', 'nombre' => 'Competencia Comunicativa en Segunda Lengua A2 Básico Principiante'],
            ['codigo' => '131635342', 'nombre' => 'Teoría del Conocimiento'],
            ['codigo' => '13164311', 'nombre' => 'Razonamiento Matemático en Vectores y Matrices'],
            ['codigo' => '131641521', 'nombre' => 'Estructuras de Datos no Lineales'],
            ['codigo' => '131642423', 'nombre' => 'Herramientas Informáticas Orientadas a Eventos'],
            ['codigo' => '131643023', 'nombre' => 'Criterios para la Selección de Hardware'],
            ['codigo' => '131643731', 'nombre' => 'Herramientas de Ingeniería Económica'],
            ['codigo' => '131644841', 'nombre' => 'Competencia Comunicativa en Segunda Lengua A3 Básico Intermedio'],
            ['codigo' => '13165411', 'nombre' => 'Procesos Estadísticos y Probabilísticos (Ing)'],
            ['codigo' => '13164711', 'nombre' => 'Cálculo Vectorial en la Computación Gráfica'],
            ['codigo' => '131651623', 'nombre' => 'Representación de Información en Base de Datos'],
            ['codigo' => '131652523', 'nombre' => 'Técnicas del Diseño Hipermedia en la Informática'],
            ['codigo' => '131663121', 'nombre' => 'Conceptos Básicos de la Comunicación Electrónica'],
            ['codigo' => '131653831', 'nombre' => 'Creatividad Empresarial y Plan de Negocios (Ing)'],
            ['codigo' => '131854941', 'nombre' => 'Competencia Comunicativa en Segunda Lengua A4 Básico Intermedio'],
            ['codigo' => '131665441', 'nombre' => 'Métodos y Técnicas de Investigación (Ing)'],
            ['codigo' => '13166511', 'nombre' => 'Modelos Matemáticos y Algoritmos'],
            ['codigo' => '131661723', 'nombre' => 'Aplicaciones Orientadas a la Web'],
            ['codigo' => '131662621', 'nombre' => 'Procesos Involucrados en el Modelado de Software'],
            ['codigo' => '131663223', 'nombre' => 'Diseño e Implementación de Redes de Datos'],
            ['codigo' => '131663931', 'nombre' => 'Formulación y Evaluación de Proyectos y Planes de Negocios (Ing)'],
            ['codigo' => '131665041', 'nombre' => 'Competencia Comunicativa en Segunda Lengua B1 Intermedio Principiante'],
            ['codigo' => '131665541', 'nombre' => 'Seminario de Grado I'],
            ['codigo' => '13167611', 'nombre' => 'Métodos Matemáticos Aplicados en Simulación'],
            ['codigo' => '131671823', 'nombre' => 'Algoritmos Lógicos en el Desarrollo de Software'],
            ['codigo' => '131672721', 'nombre' => 'Técnicas para el Desarrollo de Software'],
            ['codigo' => '131673321', 'nombre' => 'Arquitectura de Sistemas Operativos'],
            ['codigo' => '131674031', 'nombre' => 'Gerencia de Proyectos Informáticos'],
            ['codigo' => '131675141', 'nombre' => 'Competencia Comunicativa en Segunda Lengua B2 Intermedio'],
            ['codigo' => '131665641', 'nombre' => 'Seminario de Grado II'],
            ['codigo' => '131675742', 'nombre' => 'Proyecto de Investigación (Ing)'],
            ['codigo' => '13168011', 'nombre' => 'Elementos Gráficos de Comunicación Visual'],
            ['codigo' => '131681921', 'nombre' => 'Modelos de Software Distribuido'],
            ['codigo' => '131682823', 'nombre' => 'Informática para el Comercio Electrónico'],
            ['codigo' => '131683423', 'nombre' => 'Técnicas para el Diseño de Aplicaciones Telemáticas'],
            ['codigo' => '131684441', 'nombre' => 'Principios y Normas del Derecho Informático'],
            ['codigo' => '131685842', 'nombre' => 'Desarrollo del Proyecto de Investigación (Ing)'],
            ['codigo' => '131692023', 'nombre' => 'Electiva (Ing)'],
            ['codigo' => '131692923', 'nombre' => 'Diseño e Implementación de Sistemas de Telemetría'],
            ['codigo' => '131693521', 'nombre' => 'Técnicas y Herramientas de Seguridad Informática'],
            ['codigo' => '131694131', 'nombre' => 'Auditorías de Sistemas'],
            ['codigo' => '131604232', 'nombre' => 'Práctica Profesional (Ing)'],
            ['codigo' => '131694541', 'nombre' => 'Leyes Éticas y Morales (Ing)'],

            // 5. TECNOLOGÍA EN DECORACIÓN DE INTERIORES
            ['codigo' => '1060101', 'nombre' => 'Interiorismo (Fundamentos de decoración)'],
            ['codigo' => '1060104', 'nombre' => 'Historia del Arte y la Decoración'],
            ['codigo' => '1060105', 'nombre' => 'Fundamentos de Obra y Restauración'],
            ['codigo' => '1060106', 'nombre' => 'Geometría Aplicada a la Decoración'],
            ['codigo' => '1060102', 'nombre' => 'Dibujo Artístico y Bocetos'],
            ['codigo' => '1060103', 'nombre' => 'Cultura, Diseño y Decoración'],
            ['codigo' => '1060108', 'nombre' => 'Deporte Formativo'],
            ['codigo' => '1060107', 'nombre' => 'Técnicas de Estudio (Decoración)'],
            ['codigo' => '1060201', 'nombre' => 'Interiorismo II (Principios de composición en la decoración)'],
            ['codigo' => '1060203', 'nombre' => 'Estilos'],
            ['codigo' => '1060204', 'nombre' => 'Dibujo y Expresión Artística'],
            ['codigo' => '1060205', 'nombre' => 'Dibujo Técnico'],
            ['codigo' => '1060202', 'nombre' => 'Taller I (Vivienda y comunicación)'],
            ['codigo' => 'DEC-MET-01', 'nombre' => 'Metodología de la Investigación (Decoración)'],
            ['codigo' => '1060301', 'nombre' => 'Interiorismo III (Espacios comerciales)'],
            ['codigo' => '1060303', 'nombre' => 'Maquetas'],
            ['codigo' => '1060403', 'nombre' => 'Tecnología de los Materiales I'],
            ['codigo' => '1060302', 'nombre' => 'Taller II (Arte decorativo y espacios comerciales)'],
            ['codigo' => '1060305', 'nombre' => 'Informática I'],
            ['codigo' => '1060401', 'nombre' => 'Interiorismo IV (Espacios gastronómicos)'],
            ['codigo' => '1060403-TEC', 'nombre' => 'Tecnología I (Técnicas constructivas)'],
            ['codigo' => '1060404', 'nombre' => 'Tecnología de los Materiales II'],
            ['codigo' => '1060402', 'nombre' => 'Taller III (Muebles y espacios gastronómicos)'],
            ['codigo' => '1060406', 'nombre' => 'Informática II'],
            ['codigo' => '1060405', 'nombre' => 'Costos (Decoración)'],
            ['codigo' => '1060408', 'nombre' => 'Inglés I (Decoración)'],
            ['codigo' => '1060501', 'nombre' => 'Interiorismo V (Stand y exposiciones)'],
            ['codigo' => '1060503', 'nombre' => 'Tecnología II (Iluminación)'],
            ['codigo' => '1060502', 'nombre' => 'Taller IV (Arte decorativo)'],
            ['codigo' => '1060504', 'nombre' => 'Electiva I (Decoración)'],
            ['codigo' => '1060506', 'nombre' => 'Informática III'],
            ['codigo' => '1060505', 'nombre' => 'Presupuestos (Decoración)'],
            ['codigo' => '1060507', 'nombre' => 'Inglés II (Decoración)'],
            ['codigo' => '1060507-SEM', 'nombre' => 'Seminario de Grado (Decoración)'],
            ['codigo' => '1060601', 'nombre' => 'Interiorismo VI (Hoteles)'],
            ['codigo' => '1060603', 'nombre' => 'Tecnología III (Instalaciones)'],
            ['codigo' => '1060606', 'nombre' => 'Arquitectura Sostenible'],
            ['codigo' => '1060602', 'nombre' => 'Taller V (Muebles y accesorios hoteles)'],
            ['codigo' => '1060604', 'nombre' => 'Electiva II (Decoración)'],
            ['codigo' => '1060607', 'nombre' => 'Ética (Decoración)'],
            ['codigo' => '1060605', 'nombre' => 'Formulación y Evaluación de Proyectos (Decoración)'],
            ['codigo' => '1060608', 'nombre' => 'Inglés III (Decoración)'],

            // 6. CONTADURÍA PÚBLICA DISTANCIA
            ['codigo' => '11601111', 'nombre' => 'Procedimientos Matemáticos'],
            ['codigo' => '11601211', 'nombre' => 'Ordenamiento Jurídico Constitucional e Institucional'],
            ['codigo' => '11602521', 'nombre' => 'Agentes Microeconómicos'],
            ['codigo' => '11601325', 'nombre' => 'Principios Básicos de Contabilidad Financiera'],
            ['codigo' => '11601425', 'nombre' => 'Administración, Entorno y Alcances'],
            ['codigo' => '11601631', 'nombre' => 'Herramientas Pedagógicas y Didácticas de la Educación a Distancia'],
            ['codigo' => '11602111', 'nombre' => 'Procesos Estadísticos y Probabilísticos'],
            ['codigo' => '11602211', 'nombre' => 'Bases Jurídicas de la Actividad Empresarial'],
            ['codigo' => 'CONT-MAC-01', 'nombre' => 'Agentes Macroeconómicos (Contaduría)'],
            ['codigo' => '11602325', 'nombre' => 'Procedimientos Contables en el Manejo de Activos'],
            ['codigo' => '11602425', 'nombre' => 'Bases Fundamentales de la Planeación'],
            ['codigo' => '11602631', 'nombre' => 'Métodos y Técnicas de Investigación (Contaduría)'],
            ['codigo' => '11603211', 'nombre' => 'Normatividad Laboral'],
            ['codigo' => '11603525', 'nombre' => 'Comportamiento Monetario Mundial y Nacional'],
            ['codigo' => '11603325', 'nombre' => 'Procedimientos Contables en el Manejo de Pasivos'],
            ['codigo' => '11603125', 'nombre' => 'Herramientas Financieras'],
            ['codigo' => '11603425', 'nombre' => 'Técnicas de Organización Empresarial'],
            ['codigo' => '11603635', 'nombre' => 'Inglés I (Contaduría)'],
            ['codigo' => '11603731', 'nombre' => 'Comprensión de Texto y Lectura Crítica (Contaduría I)'],
            ['codigo' => '11604111', 'nombre' => 'Normatividad sobre Contratación Estatal'],
            ['codigo' => '11604525', 'nombre' => 'Mercados'],
            ['codigo' => '11604225', 'nombre' => 'Procedimientos Contables de Patrimonio y Sociedades'],
            ['codigo' => '11604325', 'nombre' => 'Gestión Financiera'],
            ['codigo' => '11604425', 'nombre' => 'Procesos de Dirección'],
            ['codigo' => '11604635', 'nombre' => 'Inglés II (Contaduría)'],
            ['codigo' => '11604731', 'nombre' => 'Comprensión de Texto y Lectura Crítica (Contaduría II)'],
            ['codigo' => '11605535', 'nombre' => 'Componentes de la Formulación de Proyectos'],
            ['codigo' => '11605125', 'nombre' => 'Informes Financieros y Matrices y Subsidiarias'],
            ['codigo' => '11606125', 'nombre' => 'Elementos del Costo por Órdenes de Producción'],
            ['codigo' => '11605225', 'nombre' => 'Registro de Operaciones Comerciales del Ciclo Contable'],
            ['codigo' => '11606725', 'nombre' => 'Normatividad Tributaria sobre IVA y Retención en la Fuente'],
            ['codigo' => '11605325', 'nombre' => 'Análisis Financiero en el Área Contable'],
            ['codigo' => '11605421', 'nombre' => 'Creatividad Empresarial y Plan de Negocios (Contaduría)'],
            ['codigo' => '11605635', 'nombre' => 'Inglés III (Contaduría)'],
            ['codigo' => '11605731', 'nombre' => 'Razonamiento Matemático (Contaduría)'],
            ['codigo' => '11607225', 'nombre' => 'Elementos del Costo por Procesos y Estándar'],
            ['codigo' => '11606223', 'nombre' => 'Herramientas Tecnológicas Aplicadas a los Sistemas Contables'],
            ['codigo' => '11606325', 'nombre' => 'El Presupuesto como Herramienta Gerencial (Contaduría)'],
            ['codigo' => '11606531', 'nombre' => 'Psicología Empresarial'],
            ['codigo' => '11606425', 'nombre' => 'Electiva I (Contaduría)'],
            ['codigo' => '11607323', 'nombre' => 'Paquetes Contables'],
            ['codigo' => '11607425', 'nombre' => 'Normatividad Tributaria sobre Impuesto de Renta y Complementarios'],
            ['codigo' => '11607525', 'nombre' => 'Normas de Auditoría y Aseguramiento'],
            ['codigo' => '11607625', 'nombre' => 'Técnicas de Control'],
            ['codigo' => '11607111', 'nombre' => 'Comercio y Normatividad Internacional'],
            ['codigo' => '11607735', 'nombre' => 'Inglés V (Contaduría)'],
            ['codigo' => '11608125', 'nombre' => 'Procedimientos Contables del Sector Público'],
            ['codigo' => '11608223', 'nombre' => 'Práctica Profesional (Contaduría)'],
            ['codigo' => '11608325', 'nombre' => 'Procedimientos Tributarios'],
            ['codigo' => '11608425', 'nombre' => 'Auditoría a los Estados Financieros'],
            ['codigo' => '11608525', 'nombre' => 'Electiva II (Contaduría)'],
            ['codigo' => '11608633', 'nombre' => 'Proyecto de Investigación (Contaduría)'],
            ['codigo' => '11608731', 'nombre' => 'Presaber Específico (Contaduría)'],
            ['codigo' => '11608535', 'nombre' => 'Inglés VI (Contaduría)'],
            ['codigo' => '11609125', 'nombre' => 'Procedimientos de Registros en Diversos Tipos de Contabilidad'],
            ['codigo' => '11609325', 'nombre' => 'Desarrollo Sostenible Aplicado al Área Contable'],
            ['codigo' => '11609425', 'nombre' => 'Procesos de Revisoría Fiscal'],
            ['codigo' => '11609533', 'nombre' => 'Desarrollo del Proyecto de Investigación (Contaduría)'],
            ['codigo' => '11609631', 'nombre' => 'Leyes Éticas y Morales (Contaduría)'],

            // 7. TECNOLOGÍA EN GESTIÓN DE LA SEGURIDAD Y SALUD EN EL TRABAJO
            ['codigo' => 'TG-SST-01', 'nombre' => 'Promoción de la Salud Laboral / Prevención de Riesgos y Peligros en Áreas de Trabajo'],
            ['codigo' => 'TG-SST-02', 'nombre' => 'Atención de Servicios de Emergencia'],
            ['codigo' => 'TG-SST-03', 'nombre' => 'Gestión y Operatividad del SG-SST'],

            // 8. INGENIERÍA INFORMÁTICA (DISTANCIA AUNAR)
            ['codigo' => '131601111', 'nombre' => 'Conceptos y Métodos Matemáticos (Distancia)'],
            ['codigo' => '131601223', 'nombre' => 'Fundamentos de Programación'],
            ['codigo' => '1316011425', 'nombre' => 'Sistemas Operativos'],
            ['codigo' => '13160151', 'nombre' => 'Responsabilidad Ciudadana e Identidad Institucional'],
            ['codigo' => '131601611', 'nombre' => 'Herramientas y Técnicas de Estudio - Educación a Distancia (Distancia)'],
            ['codigo' => '131602111', 'nombre' => 'Lógica Booleana'],
            ['codigo' => '131602211', 'nombre' => 'Cálculo Diferencial'],
            ['codigo' => '131602311', 'nombre' => 'Electromagnetismo'],
            ['codigo' => '131602423', 'nombre' => 'Programación (Distancia)'],
            ['codigo' => '131602623', 'nombre' => 'Sistemas Operativos II'],
            ['codigo' => '131602711', 'nombre' => 'Taller de Comunicación Oral y Escrita'],
            ['codigo' => '131602815', 'nombre' => 'Inglés A11'],
            ['codigo' => '131603111', 'nombre' => 'Álgebra Lineal'],
            ['codigo' => '131603211', 'nombre' => 'Cálculo Integral'],
            ['codigo' => '131603314', 'nombre' => 'Electrónica Analógica'],
            ['codigo' => '131603423', 'nombre' => 'Programación POO (Distancia)'],
            ['codigo' => '131603523', 'nombre' => 'Estructuras de Datos'],
            ['codigo' => '131603611', 'nombre' => 'Gestión Estratégica y Empresarial'],
            ['codigo' => '131603715', 'nombre' => 'Inglés A12'],
            ['codigo' => '131603811', 'nombre' => 'Epistemología de la Investigación'],
            ['codigo' => '131605111', 'nombre' => 'Probabilidad y Estadística (Distancia)'],
            ['codigo' => '131604111', 'nombre' => 'Cálculo Multivariable'],
            ['codigo' => '131604214', 'nombre' => 'Electrónica Digital'],
            ['codigo' => '131604323', 'nombre' => 'Programación Móvil y Sistemas Embebidos'],
            ['codigo' => '131604423', 'nombre' => 'Bases de Datos (Distancia)'],
            ['codigo' => '131605323', 'nombre' => 'Estructuras de Datos II'],
            ['codigo' => '131604511', 'nombre' => 'Creatividad e Innovación Empresarial (Distancia)'],
            ['codigo' => '131605611', 'nombre' => 'Emprendimiento y Plan de Negocios (Distancia)'],
            ['codigo' => '131604611', 'nombre' => 'Seminario de Desarrollo Humano I (Habilidades Humanas)'],
            ['codigo' => '131604715', 'nombre' => 'Inglés A21'],
            ['codigo' => '131604811', 'nombre' => 'Investigación Pura y Aplicada'],
            ['codigo' => '131605223', 'nombre' => 'Programación POO II'],
            ['codigo' => '131605424', 'nombre' => 'Comunicación Electrónica (Distancia)'],
            ['codigo' => '131605523', 'nombre' => 'Electiva (Distancia)'],
            ['codigo' => '131605711', 'nombre' => 'Seminario de Desarrollo Humano II (Habilidades Cognitivas)'],
            ['codigo' => '131605815', 'nombre' => 'Inglés A22'],
            ['codigo' => '131606111', 'nombre' => 'Investigación de Operaciones (Distancia)'],
            ['codigo' => '131606225', 'nombre' => 'Big Data'],
            ['codigo' => '131606323', 'nombre' => 'Bases de Datos II (Distancia)'],
            ['codigo' => '133606423', 'nombre' => 'Redes de Datos (Distancia)'],
            ['codigo' => '131606523', 'nombre' => 'Electiva II (Distancia)'],
            ['codigo' => '13160611', 'nombre' => 'Formulación y Evaluación de Proyectos (Distancia)'],
            ['codigo' => '131606711', 'nombre' => 'Seminario de Desarrollo Humano III (Habilidades Sociales)'],
            ['codigo' => '131606815', 'nombre' => 'Inglés B11'],
            ['codigo' => '131606925', 'nombre' => 'Seminario de Grado (Propuesta)'],
            ['codigo' => '131607111', 'nombre' => 'Simulación Digital'],
            ['codigo' => '131607225', 'nombre' => 'Inteligencia Computacional I'],
            ['codigo' => '131607323', 'nombre' => 'Programación Web / Front End'],
            ['codigo' => '131607423', 'nombre' => 'Ingeniería de Software'],
            ['codigo' => '131607523', 'nombre' => 'Telemática'],
            ['codigo' => '131607623', 'nombre' => 'Hacking'],
            ['codigo' => '131607715', 'nombre' => 'Inglés B12'],
            ['codigo' => '131607825', 'nombre' => 'Seminario de Grado II (Anteproyecto)'],
            ['codigo' => '131608123', 'nombre' => 'Inteligencia Computacional II'],
            ['codigo' => '131608223', 'nombre' => 'Programación Web Back End'],
            ['codigo' => '131608323', 'nombre' => 'Sistemas Distribuidos'],
            ['codigo' => '131608423', 'nombre' => 'Sistemas de Telemetría'],
            ['codigo' => '131608525', 'nombre' => 'Sistemas de Gestión de Seguridad de la Información'],
            ['codigo' => '131608611', 'nombre' => 'Gestión de Proyectos Tecnológicos'],
            ['codigo' => '131608723', 'nombre' => 'Desarrollo de Trabajo de Grado I'],
            ['codigo' => '131609123', 'nombre' => 'Electiva III (Distancia)'],
            ['codigo' => '131609223', 'nombre' => 'Práctica Profesional (Distancia)'],
            ['codigo' => '131609311', 'nombre' => 'Leyes Éticas y Morales (Distancia)'],
            ['codigo' => '131609411', 'nombre' => 'Principios y Normas del Derecho Informático (Distancia)'],
            ['codigo' => '131609523', 'nombre' => 'Desarrollo de Trabajo de Grado II'],
        ];

        foreach ($asignaturas as $data) {
            Asignatura::updateOrCreate(
                ['nombre' => $data['nombre']],
                [
                    'codigo' => $data['codigo'],
                    'creditos' => 3,
                    'tipo' => 'Teórico',
                    'estado' => 'Activo'
                ]
            );
        }
    }
}